name: Cross-platform CMake Builds

on: [push, pull_request]

jobs:
  build:
    name: Create Debug and Release builds with CMake on Ubuntu
    runs-on: ${{ matrix.os }}
    if: |
      !contains(format('{0} {1} {2}', github.event.head_commit.message, github.event.pull_request.title, github.event.pull_request.body), '[skip ci]')
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        type: [Debug, Release]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install latest CMake
        uses: lukka/get-cmake@latest

      - name: Run CMake with regular Unix Makefiles
        uses: lukka/run-cmake@v2
        with:
          cmakeListsOrSettingsJson: "CMakeListsTxtBasic"
          cmakeBuildType: ${{ matrix.type }}
          buildDirectory: "${{ github.workspace }}/${{ matrix.type }}"

      - name: Run the built executable
        run: ${{ github.workspace }}/${{ matrix.type }}/main
